parse-server:
  build: .
  volumes:
    - .:/data/db
  ports:
    - "1337:1337"
  links:
    - mongo
  environment:
    APP_ID: setYourAppId
    MASTER_KEY: setYourMasterKey
    CLIENT_KEY: setYourClientKey
    DATABASE_URI: mongodb://mongo:27017/dev
mongo:
  image: mongo:3.2.1
  expose:
    - 27017
  volumes:
    - /data/db
parse-dashboard:
  build: parse-dashboard/
  links:
    - parse-server
  ports:
    - "4040:4040"
  environment:
    PARSE_DASHBOARD_SERVER_URL: http://192.168.99.100:1337/parse
    PARSE_DASHBOARD_MASTER_KEY: setYourMasterKey
    PARSE_DASHBOARD_APP_ID: setYourAppId
    PARSE_DASHBOARD_APP_NAME: setAppName
    PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: Y
    PARSE_DASHBOARD_USER_ID: admin
    PARSE_DASHBOARD_USER_PASSWORD: password
